# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-24 00:25
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160823_2328'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='color',
            field=colorfield.fields.ColorField(default='#000000', max_length=10),
        ),
    ]
