# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-15 01:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160713_0210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videofile',
        ),
        migrations.AddField(
            model_name='video',
            name='videolink',
            field=models.URLField(default='nolink', max_length=500),
            preserve_default=False,
        ),
    ]
