# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-28 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160826_0137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='videotag', to='app.Tag'),
        ),
    ]
