# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20160727_1710'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexSlide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='index/slides/')),
                ('order', models.IntegerField(default=0)),
            ],
        ),
    ]
