# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-28 20:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_indexslide'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadOfInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('wechat', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='users/images/default.jpg', upload_to='users/images/'),
        ),
        migrations.AddField(
            model_name='headofinfo',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.User'),
        ),
    ]
