# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 04:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_help_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, default='2016-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
