# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 03:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20160811_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userarticles', to=settings.AUTH_USER_MODEL),
        ),
    ]
