# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 04:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20160811_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articletag', to='app.Tag'),
        ),
    ]
