# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 21:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20160812_2038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
