# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-18 21:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_childcomment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='childcomment',
            options={'ordering': ['-dt_created']},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-dt_created']},
        ),
    ]
