# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 02:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('summary', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(default='articleimages/noimage.gif', upload_to='articleimages/')),
                ('views', models.IntegerField(default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleLink',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('link', models.URLField()),
                ('summary', models.CharField(max_length=500, null=True)),
                ('image', models.ImageField(default='articleimages/noimage.gif', upload_to='articles/images/')),
                ('views', models.IntegerField(default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('resourcefile', models.FileField(upload_to='resources/')),
                ('filetype', models.CharField(max_length=5)),
                ('summary', models.CharField(max_length=500, null=True)),
                ('views', models.IntegerField(default=0)),
                ('downloads', models.IntegerField(default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('completed', models.BooleanField(default=False)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('dt_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('videofile', models.FileField(upload_to='videos/')),
                ('summary', models.CharField(max_length=500, null=True)),
                ('speaker', models.CharField(max_length=50, null=True)),
                ('views', models.IntegerField(default=0)),
                ('dt_created', models.DateTimeField(auto_now_add=True)),
                ('poster', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uservideos', to='app.User')),
                ('tags', models.ManyToManyField(related_name='videotag', to='app.Tag')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='user',
            unique_together=set([('id', 'username')]),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teammembers', to='app.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taskleaders', to='app.User'),
        ),
        migrations.AddField(
            model_name='task',
            name='members',
            field=models.ManyToManyField(related_name='taskmembers', to='app.User'),
        ),
        migrations.AddField(
            model_name='resource',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userresources', to='app.User'),
        ),
        migrations.AddField(
            model_name='resource',
            name='tags',
            field=models.ManyToManyField(related_name='resourcetag', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='resource',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teamresources', to='app.Team'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='poster',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userarticlelinks', to='app.User'),
        ),
        migrations.AddField(
            model_name='articlelink',
            name='tags',
            field=models.ManyToManyField(related_name='articlelinktag', to='app.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userarticles', to='app.User'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articletag', to='app.Tag'),
        ),
    ]
