# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-27 17:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20160727_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='articles/images/noimage.png', upload_to='articles/images/'),
        ),
    ]
