# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20160802_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='help',
            name='faq',
            field=models.BooleanField(default=False),
        ),
    ]
