# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-12 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_info_fullname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='info',
            name='fullname',
            field=models.CharField(max_length=100),
        ),
    ]
