# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-22 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_team_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='summary',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
